# Generated by Django 4.2.1 on 2023-06-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedvideoitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
